# Указываем базовый образ Ubuntu 18.04
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
  
    # Настройки виртуальной машины
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    # Скрипт, который выполнится при запуске машины
    config.vm.provision "shell", inline: <<-SHELL
      # Обновление списка пакетов и установка Python3, pip и необходимых библиотек
      sudo apt update
      sudo apt install -y python3 python3-pip
      pip3 install psycopg2 Django
    SHELL
  
    # Копирование пустого файла на ВМ
    config.vm.provision "file", source: "~/Desktop/empty_file.txt", destination: "/home/vagrant/empty_file.txt"
  end
  